name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get lspatch and Roaming
        run: wget https://github.com/LSPosed/LSPatch/releases/download/v0.3.1/lspatch.jar
             wget https://github.com/yujincheng08/BiliRoaming/releases/download/v1.6.4/BiliRoaming_1.6.4.apk
             ls
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
